Repository performancecopilot/pcp, pull requests merged in 2019-05, with the labels that each got.

#633 pmdabcc: extend README
  src/pmdas/bcc/README
  src/pmdas/bcc/README.md
Labels: docs

#634 pcp-dstat: fix typo in printtype detection
  src/pcp/dstat/pcp-dstat.py
Labels: docs

#640 pmproxy: fix memory leaks picked up by coverity scanning
  src/pmproxy/src/grafana.c
  src/pmproxy/src/http.c
  src/pmproxy/src/series.c
Labels: bug

#649 pcp-dstat: fix --bits option
  qa/1187
  qa/1187.out
  src/pcp/dstat/pcp-dstat.py
Labels: bug

#648 logutil: add -m option to pmlogcheck to skip log volume checking
  man/man1/pmlogcheck.1
  src/pcp/dmcache/pcp-dmcache.py
  src/pmlogcheck/pmlogcheck.c
Labels: feature
